# -*- coding: utf-8 -*-
"""random forest_scikit-learn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1os7TpTPTfRVGnf_FN4Iis6TlytVy21qt
"""

# Train-test split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=42)

# Train first model (store in memory)
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X1_train, y1_train)
y1_pred = rf_model.predict(X1_test)

# First model evaluation
acc1 = accuracy_score(y1_test, y1_pred)
cm1 = confusion_matrix(y1_test, y1_pred)

print("\n📊 First Model Results")
print("Accuracy:", acc1)
print(classification_report(y1_test, y1_pred))

plt.figure(figsize=(6, 4))
sns.heatmap(cm1, annot=True, fmt="d", cmap="Blues", xticklabels=rf_model.classes_, yticklabels=rf_model.classes_)
plt.title("Confusion Matrix: Attacker Model")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()
