# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h345G58hyKEU8_9c0-PIUnn9MmG80ivV
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from google.colab import files
import io

# Function to encode ports if needed
def encode_ports(df):
    le_src = LabelEncoder()
    le_dst = LabelEncoder()
    if df['Source Port'].dtype == 'object':
        df['Source Port'] = le_src.fit_transform(df['Source Port'])
    if df['Destination Port'].dtype == 'object':
        df['Destination Port'] = le_dst.fit_transform(df['Destination Port'])
    return df

# Upload First Dataset
print("🔼 Upload the FIRST dataset:")
uploaded = files.upload()
for fname in uploaded.keys():
    df1 = pd.read_csv(io.BytesIO(uploaded[fname]))

df1.rename(columns=lambda x: x.strip(), inplace=True)
df1 = encode_ports(df1)

assert all(col in df1.columns for col in ['Source Port', 'Destination Port', 'Device'])

X1 = df1[['Source Port', 'Destination Port']]
y1 = df1['Device']

# Train-test split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=42)

# Train first model (store in memory)
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X1_train, y1_train)
y1_pred = rf_model.predict(X1_test)

# First model evaluation
acc1 = accuracy_score(y1_test, y1_pred)
cm1 = confusion_matrix(y1_test, y1_pred)

print("\n📊 First Model Results")
print("Accuracy:", acc1)
print(classification_report(y1_test, y1_pred))

plt.figure(figsize=(6, 4))
sns.heatmap(cm1, annot=True, fmt="d", cmap="Blues", xticklabels=rf_model.classes_, yticklabels=rf_model.classes_)
plt.title("Confusion Matrix: Attacker Model")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Upload Second Dataset
print("\n🔼 Upload the SECOND dataset:")
uploaded2 = files.upload()
for fname2 in uploaded2.keys():
    df2 = pd.read_csv(io.BytesIO(uploaded2[fname2]))

df2.rename(columns=lambda x: x.strip(), inplace=True)
df2.rename(columns={
    'source port': 'Source Port',
    'destination port': 'Destination Port',
    'device': 'Device'
}, inplace=True)
df2 = encode_ports(df2)

assert all(col in df2.columns for col in ['Source Port', 'Destination Port', 'Device'])

X2 = df2[['Source Port', 'Destination Port']]
y2 = df2['Device']

# Use the first model to predict on the second dataset
y2_pred = rf_model.predict(X2)

# Evaluation on second dataset
acc2 = accuracy_score(y2, y2_pred)
cm2 = confusion_matrix(y2, y2_pred)

print("\n📊 First Model Tested on Second Dataset")
print("Accuracy:", acc2)
print(classification_report(y2, y2_pred))

plt.figure(figsize=(6, 4))
sns.heatmap(cm2, annot=True, fmt="d", cmap="Greens", xticklabels=rf_model.classes_, yticklabels=rf_model.classes_)
plt.title("Pool of Dummy")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Accuracy comparison
plt.figure(figsize=(6, 4))
plt.bar(['First Dataset', 'Second Dataset'], [acc1, acc2], color=['steelblue', 'mediumseagreen'])
plt.title("Accuracy Comparison (Same Model)")
plt.ylabel("Accuracy")
plt.ylim(0, 1)
plt.grid(True, axis='y')
plt.show()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from google.colab import files
import io
import random

# Function to encode ports if needed
def encode_ports(df):
    le_src = LabelEncoder()
    le_dst = LabelEncoder()
    if df['Source Port'].dtype == 'object':
        df['Source Port'] = le_src.fit_transform(df['Source Port'])
    if df['Destination Port'].dtype == 'object':
        df['Destination Port'] = le_dst.fit_transform(df['Destination Port'])
    return df

# 🔼 Upload First Dataset
print("🔼 Upload the FIRST dataset:")
uploaded = files.upload()
for fname in uploaded.keys():
    df1 = pd.read_csv(io.BytesIO(uploaded[fname]))

df1_encoded = encode_ports(df1.copy())

# ✅ Train First Model
X1 = df1_encoded[['Source Port', 'Destination Port']]
y1 = df1_encoded['Device']
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=42)
rf_model1 = RandomForestClassifier(random_state=42)
rf_model1.fit(X1_train, y1_train)
y1_pred = rf_model1.predict(X1_test)

print("\n📊 First Model Results")
print("Accuracy:", accuracy_score(y1_test, y1_pred))
print(classification_report(y1_test, y1_pred))

cm1 = confusion_matrix(y1_test, y1_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm1, annot=True, fmt="d", cmap="Blues", xticklabels=rf_model1.classes_, yticklabels=rf_model1.classes_)
plt.title("Confusion Matrix: First Model")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ✅ Modify Dataset Using Mixing Rules

df_mixed = df1.copy()
devices = df_mixed['Device'].unique()
valid_devices = [dev for dev in devices if dev.lower() != 'other']
device_indices = {dev: df_mixed[df_mixed['Device'] == dev].index.tolist() for dev in valid_devices}

device_types = list(device_indices.keys())
mix_pairs = []

# Create pairs from all device types
for i in range(len(device_types)):
    for j in range(i + 1, len(device_types)):
        dev1, dev2 = device_types[i], device_types[j]
        idx1 = device_indices[dev1]
        idx2 = device_indices[dev2]

        max_len = max(len(idx1), len(idx2))
        idx1 *= (max_len // len(idx1)) + 1
        idx2 *= (max_len // len(idx2)) + 1

        mix_pairs.extend(list(zip(idx1[:max_len], idx2[:max_len])))

# Mix function
def mix_values(val1, val2):
    val1, val2 = str(val1), str(val2)
    mixed = ''
    for a, b in zip(val1, val2):
        mixed += random.choice([a, b])
    if len(val1) < len(val2):
        mixed += val2[len(val1):]
    elif len(val2) < len(val1):
        mixed += val1[len(val2):]
    return mixed[:len(val1)]  # Ensure same length as original

# Apply mixing
for idx1, idx2 in mix_pairs:
    for col in ['Source Port', 'Destination Port']:
        v1, v2 = str(df_mixed.at[idx1, col]), str(df_mixed.at[idx2, col])
        if v1 != v2:
            df_mixed.at[idx1, col] = mix_values(v1, v2)
            df_mixed.at[idx2, col] = mix_values(v2, v1)

# Restore 'Other' rows to original
df_mixed.loc[df1['Device'].str.lower() == 'other'] = df1.loc[df1['Device'].str.lower() == 'other']

# ✅ Train Second Model using the modified dataset
df_mixed_encoded = encode_ports(df_mixed.copy())
X2 = df_mixed_encoded[['Source Port', 'Destination Port']]
y2 = df_mixed_encoded['Device']
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.2, random_state=42)
rf_model2 = RandomForestClassifier(random_state=42)
rf_model2.fit(X2_train, y2_train)
y2_pred = rf_model2.predict(X2_test)

print("\n📊 Traffic Shaping Confusion Metric")
print("Accuracy:", accuracy_score(y2_test, y2_pred))
print(classification_report(y2_test, y2_pred))

cm2 = confusion_matrix(y2_test, y2_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm2, annot=True, fmt="d", cmap="Greens", xticklabels=rf_model2.classes_, yticklabels=rf_model2.classes_)
plt.title("Traffic Shaping")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# 🔁 Compare Accuracy
acc1 = accuracy_score(y1_test, y1_pred)
acc2 = accuracy_score(y2_test, y2_pred)
plt.figure(figsize=(6, 4))
plt.bar(['First Model', 'Second Model'], [acc1, acc2], color=['steelblue', 'mediumseagreen'])
plt.title("Accuracy Comparison")
plt.ylabel("Accuracy")
plt.ylim(0, 1)
plt.grid(True, axis='y')
plt.show()

# HYBRID METHOD: Mix original dataset -> Train second model with mixed data -> Test with same model on pool of dummy

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from google.colab import files
import io
import random

def encode_ports(df):
    le_src = LabelEncoder()
    le_dst = LabelEncoder()
    if df['Source Port'].dtype == 'object':
        df['Source Port'] = le_src.fit_transform(df['Source Port'])
    if df['Destination Port'].dtype == 'object':
        df['Destination Port'] = le_dst.fit_transform(df['Destination Port'])
    return df

def mix_source_ports(df):
    df_mixed = df.copy()
    devices = df_mixed['Device'].unique()
    valid_devices = [dev for dev in devices if dev.lower() != 'other']
    device_indices = {dev: df_mixed[df_mixed['Device'] == dev].index.tolist() for dev in valid_devices}

    mix_pairs = []
    device_types = list(device_indices.keys())
    for i in range(len(device_types)):
        for j in range(i + 1, len(device_types)):
            idx1 = device_indices[device_types[i]]
            idx2 = device_indices[device_types[j]]
            max_len = max(len(idx1), len(idx2))
            idx1 *= (max_len // len(idx1)) + 1
            idx2 *= (max_len // len(idx2)) + 1
            mix_pairs.extend(list(zip(idx1[:max_len], idx2[:max_len])))

    for idx1, idx2 in mix_pairs:
        v1, v2 = str(df_mixed.at[idx1, 'Source Port']), str(df_mixed.at[idx2, 'Source Port'])
        if v1 != v2:
            df_mixed.at[idx1, 'Source Port'] = v2
            df_mixed.at[idx2, 'Source Port'] = v1

    df_mixed.loc[df['Device'].str.lower() == 'other'] = df.loc[df['Device'].str.lower() == 'other']
    return df_mixed

# Step 1: Upload and mix the first dataset
print("🔼 Upload the FIRST dataset:")
uploaded = files.upload()
for fname in uploaded.keys():
    df1 = pd.read_csv(io.BytesIO(uploaded[fname]))

df1.rename(columns=lambda x: x.strip(), inplace=True)
df1_mixed = mix_source_ports(df1)
df1_encoded = encode_ports(df1_mixed.copy())

X1 = df1_encoded[['Source Port', 'Destination Port']]
y1 = df1_encoded['Device']


# Train the model on mixed data
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=42)
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X1_train, y1_train)

# Step 2: Upload the second dataset (dummy pool) and evaluate
print("\n🔼 Upload the SECOND dataset (dummy pool):")
uploaded2 = files.upload()
for fname2 in uploaded2.keys():
    df2 = pd.read_csv(io.BytesIO(uploaded2[fname2]))

df2.rename(columns=lambda x: x.strip(), inplace=True)
df2.rename(columns={'source port': 'Source Port', 'destination port': 'Destination Port', 'device': 'Device'}, inplace=True)
df2_encoded = encode_ports(df2.copy())

X2 = df2_encoded[['Source Port', 'Destination Port']]
y2 = df2_encoded['Device']
y2_pred = rf_model.predict(X2)

print("\n📊 Hybrid Method Results")
print("Accuracy:", accuracy_score(y2, y2_pred))
print(classification_report(y2, y2_pred, zero_division=0))


cm = confusion_matrix(y2, y2_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Purples", xticklabels=rf_model.classes_, yticklabels=rf_model.classes_)
plt.title("Confusion Matrix: Hybrid Method")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# MULTISTAGE METHOD: Train on original dataset -> Test on second dataset -> Mix second dataset -> Test again

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from google.colab import files
import io
import random

def encode_ports(df):
    le_src = LabelEncoder()
    le_dst = LabelEncoder()
    if df['Source Port'].dtype == 'object':
        df['Source Port'] = le_src.fit_transform(df['Source Port'])
    if df['Destination Port'].dtype == 'object':
        df['Destination Port'] = le_dst.fit_transform(df['Destination Port'])
    return df

def mix_source_ports(df):
    df_mixed = df.copy()
    devices = df_mixed['Device'].unique()
    valid_devices = [dev for dev in devices if dev.lower() != 'other']
    device_indices = {dev: df_mixed[df_mixed['Device'] == dev].index.tolist() for dev in valid_devices}

    mix_pairs = []
    device_types = list(device_indices.keys())
    for i in range(len(device_types)):
        for j in range(i + 1, len(device_types)):
            idx1 = device_indices[device_types[i]]
            idx2 = device_indices[device_types[j]]
            max_len = max(len(idx1), len(idx2))
            idx1 *= (max_len // len(idx1)) + 1
            idx2 *= (max_len // len(idx2)) + 1
            mix_pairs.extend(list(zip(idx1[:max_len], idx2[:max_len])))

    for idx1, idx2 in mix_pairs:
        v1, v2 = str(df_mixed.at[idx1, 'Source Port']), str(df_mixed.at[idx2, 'Source Port'])
        if v1 != v2:
            df_mixed.at[idx1, 'Source Port'] = v2
            df_mixed.at[idx2, 'Source Port'] = v1

    df_mixed.loc[df['Device'].str.lower() == 'other'] = df.loc[df['Device'].str.lower() == 'other']
    return df_mixed

# Step 1: Train on original dataset
print("🔼 Upload the FIRST dataset:")
uploaded = files.upload()
for fname in uploaded.keys():
    df1 = pd.read_csv(io.BytesIO(uploaded[fname]))

df1.rename(columns=lambda x: x.strip(), inplace=True)
df1_encoded = encode_ports(df1.copy())

X1 = df1_encoded[['Source Port', 'Destination Port']]
y1 = df1_encoded['Device']
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=42)

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X1_train, y1_train)

# Step 2: Upload dummy pool
print("\n🔼 Upload the SECOND dataset (dummy pool):")
uploaded2 = files.upload()
for fname2 in uploaded2.keys():
    df2 = pd.read_csv(io.BytesIO(uploaded2[fname2]))

df2.rename(columns=lambda x: x.strip(), inplace=True)
df2.rename(columns={'source port': 'Source Port', 'destination port': 'Destination Port', 'device': 'Device'}, inplace=True)

# First evaluation on dummy pool
df2_encoded = encode_ports(df2.copy())
X2 = df2_encoded[['Source Port', 'Destination Port']]
y2 = df2_encoded['Device']
y2_pred_1 = rf_model.predict(X2)

print("\n📊 Multistage Step 1: Original Dummy Dataset")
print("Accuracy:", accuracy_score(y2, y2_pred_1))
print(classification_report(y2, y2_pred_1))

# Step 3: Mix dummy dataset and re-evaluate
df2_mixed = mix_source_ports(df2)
df2_mixed_encoded = encode_ports(df2_mixed.copy())
X2_mixed = df2_mixed_encoded[['Source Port', 'Destination Port']]
y2_mixed = df2_mixed_encoded['Device']
y2_pred_2 = rf_model.predict(X2_mixed)

print("\n📊 Multistage Step 2: Mixed Dummy Dataset")
print("Accuracy:", accuracy_score(y2_mixed, y2_pred_2))
print(classification_report(y2_mixed, y2_pred_2))

# Plot confusion matrix
plt.figure(figsize=(6, 4))
sns.heatmap(confusion_matrix(y2_mixed, y2_pred_2), annot=True, fmt="d", cmap="Oranges", xticklabels=rf_model.classes_, yticklabels=rf_model.classes_)
plt.title("Confusion Matrix: Multistage")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

import sys
import io
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, precision_score
from google.colab import files
import random

# ========== Helper Functions ==========
def encode_ports(df):
    le_src = LabelEncoder()
    le_dst = LabelEncoder()
    if df['Source Port'].dtype == 'object':
        df['Source Port'] = le_src.fit_transform(df['Source Port'].astype(str))
    if df['Destination Port'].dtype == 'object':
        df['Destination Port'] = le_dst.fit_transform(df['Destination Port'].astype(str))
    return df

def mix_source_ports(df):
    df_mixed = df.copy()
    devices = df_mixed['Device'].unique()
    valid_devices = [dev for dev in devices if dev.lower() != 'other']
    device_indices = {dev: df_mixed[df_mixed['Device'] == dev].index.tolist() for dev in valid_devices}

    mix_pairs = []
    device_types = list(device_indices.keys())
    for i in range(len(device_types)):
        for j in range(i + 1, len(device_types)):
            idx1 = device_indices[device_types[i]]
            idx2 = device_indices[device_types[j]]
            max_len = max(len(idx1), len(idx2))
            idx1 *= (max_len // len(idx1)) + 1
            idx2 *= (max_len // len(idx2)) + 1
            mix_pairs.extend(list(zip(idx1[:max_len], idx2[:max_len])))

    for idx1, idx2 in mix_pairs:
        v1, v2 = df_mixed.at[idx1, 'Source Port'], df_mixed.at[idx2, 'Source Port']
        df_mixed.at[idx1, 'Source Port'] = v2
        df_mixed.at[idx2, 'Source Port'] = v1

    df_mixed.loc[df['Device'].str.lower() == 'other'] = df.loc[df['Device'].str.lower() == 'other']
    return df_mixed

def mix_ports(df):
    df_mixed = df.copy()
    devices = df_mixed['Device'].unique()
    valid_devices = [dev for dev in devices if dev.lower() != 'other']
    device_indices = {dev: df_mixed[df_mixed['Device'] == dev].index.tolist() for dev in valid_devices}

    device_types = list(device_indices.keys())
    mix_pairs = []

    for i in range(len(device_types)):
        for j in range(i + 1, len(device_types)):
            idx1 = device_indices[device_types[i]]
            idx2 = device_indices[device_types[j]]
            max_len = max(len(idx1), len(idx2))
            idx1 *= (max_len // len(idx1)) + 1
            idx2 *= (max_len // len(idx2)) + 1
            mix_pairs.extend(list(zip(idx1[:max_len], idx2[:max_len])))

    def mix_values(val1, val2):
        val1, val2 = str(val1), str(val2)
        mixed = ''
        for a, b in zip(val1, val2):
            mixed += random.choice([a, b])
        if len(val1) < len(val2):
            mixed += val2[len(val1):]
        elif len(val2) < len(val1):
            mixed += val1[len(val2):]
        return mixed[:len(val1)]

    for idx1, idx2 in mix_pairs:
        for col in ['Source Port', 'Destination Port']:
            v1, v2 = str(df_mixed.at[idx1, col]), str(df_mixed.at[idx2, col])
            if v1 != v2:
                df_mixed.at[idx1, col] = mix_values(v1, v2)
                df_mixed.at[idx2, col] = mix_values(v2, v1)

    df_mixed.loc[df['Device'].str.lower() == 'other'] = df.loc[df['Device'].str.lower() == 'other']
    return df_mixed

def calculate_feature_variance(df):
    """Calculates the variance of the features (Source Port, Destination Port), handling non-numeric values."""
    # Ensure that the 'Source Port' and 'Destination Port' are numeric
    df['Source Port'] = pd.to_numeric(df['Source Port'], errors='coerce')
    df['Destination Port'] = pd.to_numeric(df['Destination Port'], errors='coerce')

    # Drop rows with NaN values in the numeric columns
    df_clean = df.dropna(subset=['Source Port', 'Destination Port'])

    # Calculate and return the variance
    return np.var(df_clean[['Source Port', 'Destination Port']], axis=0).mean()

# ========== Upload First Dataset ==========
print("🔼 Upload the FIRST dataset:")
uploaded = files.upload()
for fname in uploaded.keys():
    df1 = pd.read_csv(io.BytesIO(uploaded[fname]))

df1.rename(columns=lambda x: x.strip(), inplace=True)
df1.rename(columns={'source port': 'Source Port', 'destination port': 'Destination Port', 'device': 'Device'}, inplace=True)
assert all(col in df1.columns for col in ['Source Port', 'Destination Port', 'Device'])

dataset_size = len(df1)
print(f"\n✅ Dataset contains {dataset_size} rows")

# Calculate feature variance for the dataset
feature_variance = calculate_feature_variance(df1)
print(f"\n📊 Feature Variance: {feature_variance}")

# ========== METHOD SELECTION ==========
# Use dataset size and feature variance to select method
if dataset_size > 40000 or feature_variance > 700000000:  # Threshold for variance can be adjusted
    method = "hybrid"
elif dataset_size > 1500:
    method = "method1"
else:
    method = "method2"

print(f"\n🚀 Using {method.upper()} based on dataset size and feature variance...")

# ========== METHOD 1 ==========
if method == "method1":
    df1 = encode_ports(df1)
    X1 = df1[['Source Port', 'Destination Port']]
    y1 = df1['Device']
    X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=42)
    rf_model = RandomForestClassifier(random_state=42)
    rf_model.fit(X1_train, y1_train)
    y1_pred = rf_model.predict(X1_test)

    print("\n📊 Method 1 Results")
    print("Accuracy:", accuracy_score(y1_test, y1_pred))
    print(classification_report(y1_test, y1_pred, zero_division=1))
    cm1 = confusion_matrix(y1_test, y1_pred)
    sns.heatmap(cm1, annot=True, fmt="d", cmap="Blues", xticklabels=rf_model.classes_, yticklabels=rf_model.classes_)
    plt.title("Confusion Matrix: Attacker Model")
    plt.show()

    print("\n🔼 Upload the Pool of Dummy dataset:")
    uploaded2 = files.upload()
    for fname2 in uploaded2.keys():
        df2 = pd.read_csv(io.BytesIO(uploaded2[fname2]))

    df2.rename(columns=lambda x: x.strip(), inplace=True)
    df2.rename(columns={'source port': 'Source Port', 'destination port': 'Destination Port', 'device': 'Device'}, inplace=True)
    df2 = encode_ports(df2)
    X2 = df2[['Source Port', 'Destination Port']]
    y2 = df2['Device']
    y2_pred = rf_model.predict(X2)

    print("\n📊 First Model on Second Dataset")
    print("Accuracy:", accuracy_score(y2, y2_pred))
    print(classification_report(y2, y2_pred, labels=rf_model.classes_, zero_division=1))
    cm2 = confusion_matrix(y2, y2_pred, labels=rf_model.classes_)
    sns.heatmap(cm2, annot=True, fmt="d", cmap="Greens", xticklabels=rf_model.classes_, yticklabels=rf_model.classes_)
    plt.title("Confusion Matrix: Pool of Dummy")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

# ========== METHOD 2 ==========
elif method == "method2":
    # ✅ Train First Model
    df1_encoded = encode_ports(df1.copy())
    X1 = df1_encoded[['Source Port', 'Destination Port']]
    y1 = df1_encoded['Device']
    X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=42)
    rf_model1 = RandomForestClassifier(random_state=42)
    rf_model1.fit(X1_train, y1_train)
    y1_pred = rf_model1.predict(X1_test)

    print("\n📊 First Model Results")
    print("Accuracy:", accuracy_score(y1_test, y1_pred))
    print(classification_report(y1_test, y1_pred))

    cm1 = confusion_matrix(y1_test, y1_pred)
    plt.figure(figsize=(6, 4))
    sns.heatmap(cm1, annot=True, fmt="d", cmap="Blues", xticklabels=rf_model1.classes_, yticklabels=rf_model1.classes_)
    plt.title("Confusion Matrix: First Model")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

    # ✅ Modify Dataset Using Mixing Rules

    df_mixed = df1.copy()
    devices = df_mixed['Device'].unique()
    valid_devices = [dev for dev in devices if dev.lower() != 'other']
    device_indices = {dev: df_mixed[df_mixed['Device'] == dev].index.tolist() for dev in valid_devices}

    device_types = list(device_indices.keys())
    mix_pairs = []

    # Create pairs from all device types
    for i in range(len(device_types)):
        for j in range(i + 1, len(device_types)):
            dev1, dev2 = device_types[i], device_types[j]
            idx1 = device_indices[dev1]
            idx2 = device_indices[dev2]

            max_len = max(len(idx1), len(idx2))
            idx1 *= (max_len // len(idx1)) + 1
            idx2 *= (max_len // len(idx2)) + 1

            mix_pairs.extend(list(zip(idx1[:max_len], idx2[:max_len])))

    # Mix function
    def mix_values(val1, val2):
        val1, val2 = str(val1), str(val2)
        mixed = ''
        for a, b in zip(val1, val2):
            mixed += random.choice([a, b])
        if len(val1) < len(val2):
            mixed += val2[len(val1):]
        elif len(val2) < len(val1):
            mixed += val1[len(val2):]
        return mixed[:len(val1)]  # Ensure same length as original


    # 🔧 Convert port columns to strings to avoid dtype mismatch warnings
    df_mixed['Source Port'] = df_mixed['Source Port'].astype(str)
    df_mixed['Destination Port'] = df_mixed['Destination Port'].astype(str)


    # Apply mixing
    for idx1, idx2 in mix_pairs:
        for col in ['Source Port', 'Destination Port']:
            v1, v2 = str(df_mixed.at[idx1, col]), str(df_mixed.at[idx2, col])
            if v1 != v2:
                df_mixed.at[idx1, col] = mix_values(v1, v2)
                df_mixed.at[idx2, col] = mix_values(v2, v1)

    # Restore 'Other' rows to original
    df_mixed.loc[df1['Device'].str.lower() == 'other'] = df1.loc[df1['Device'].str.lower() == 'other']

    # ✅ Train Second Model using the modified dataset
    df_mixed_encoded = encode_ports(df_mixed.copy())
    X2 = df_mixed_encoded[['Source Port', 'Destination Port']]
    y2 = df_mixed_encoded['Device']
    X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.2, random_state=42)
    rf_model2 = RandomForestClassifier(random_state=42)
    rf_model2.fit(X2_train, y2_train)
    y2_pred = rf_model2.predict(X2_test)

    print("\n📊 Second Model Results (Mixed Dataset)")
    print("Accuracy:", accuracy_score(y2_test, y2_pred))
    print(classification_report(y2_test, y2_pred))

    cm2 = confusion_matrix(y2_test, y2_pred)
    plt.figure(figsize=(6, 4))
    sns.heatmap(cm2, annot=True, fmt="d", cmap="Reds", xticklabels=rf_model2.classes_, yticklabels=rf_model2.classes_)
    plt.title("Confusion Matrix: Traffic Shaping")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()



# ========== HYBRID METHOD ==========
elif method == "hybrid":
    df1_mixed = mix_source_ports(df1)
    df1_mixed = encode_ports(df1_mixed)
    X1 = df1_mixed[['Source Port', 'Destination Port']]
    y1 = df1_mixed['Device']
    X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=42)
    rf_model = RandomForestClassifier(random_state=42)
    rf_model.fit(X1_train, y1_train)
    y1_pred = rf_model.predict(X1_test)

    print("\n📊 Hybrid Method: Attacker Models")
    print("Accuracy:", accuracy_score(y1_test, y1_pred))
    print(classification_report(y1_test, y1_pred, zero_division=1))
    cm1 = confusion_matrix(y1_test, y1_pred)
    sns.heatmap(cm1, annot=True, fmt="d", cmap="Blues", xticklabels=rf_model.classes_, yticklabels=rf_model.classes_)
    plt.title("Confusion Matrix: Attacker Model")
    plt.show()

    print("\n🔼 Upload the SECOND dataset:")
    uploaded2 = files.upload()
    for fname2 in uploaded2.keys():
        df2 = pd.read_csv(io.BytesIO(uploaded2[fname2]))

    df2.rename(columns=lambda x: x.strip(), inplace=True)
    df2.rename(columns={'source port': 'Source Port', 'destination port': 'Destination Port', 'device': 'Device'}, inplace=True)
    df2_mixed = mix_source_ports(df2)
    df2_mixed = encode_ports(df2_mixed)
    X2 = df2_mixed[['Source Port', 'Destination Port']]
    y2 = df2_mixed['Device']
    y2_pred = rf_model.predict(X2)

    print("\n📊 Hybrid Defense")
    print("Accuracy:", accuracy_score(y2, y2_pred))
    print(classification_report(y2, y2_pred, labels=rf_model.classes_, zero_division=1))
    cm2 = confusion_matrix(y2, y2_pred, labels=rf_model.classes_)
    sns.heatmap(cm2, annot=True, fmt="d", cmap="Purples", xticklabels=rf_model.classes_, yticklabels=rf_model.classes_)
    plt.title("Confusion Matrix: Hybrid Method ")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

import matplotlib.pyplot as plt

# Defense methods and their corresponding accuracies
methods = [
    "Attacker Model",
    "Method 1 (Dummy Pool)",
    "MITRA (Santos et al., 2023)",
    "T-SNERF (Hammad et al., 2021)",
    "GIWRF (Khan et al., 2021)",
]

accuracies = [
    99.98,  # Attacker Model
    67.78,  # Method 1 (Dummy Pool)
    48.00,  # MITRA
    98.78,  # T-SNERF
    74.87,  # GIWRF
]

# Create the line chart
plt.figure(figsize=(10, 6))
plt.plot(methods, accuracies, marker='o', linestyle='-', color='blue', label='Accuracy')

# Highlight Method 1 (Dummy Pool)
highlight_index = methods.index("Method 1 (Dummy Pool)")
plt.scatter(methods[highlight_index], accuracies[highlight_index], color='red', s=100, label='Pool of Dummy')

# Annotate the highlighted point
plt.annotate(f"{accuracies[highlight_index]}%",
             (methods[highlight_index], accuracies[highlight_index] + 1),
             color='red', ha='center')

# Chart labels and title
plt.title("Comparison of Defense Mechanisms Methods")
plt.xlabel("Defense Methods")
plt.ylabel("Accuracy (%)")
plt.ylim(40, 110)
plt.grid(True)
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Labels and values
methods = ['Attacker Model', 'Traffic Shaping Model']
accuracies = [99.98, 77.12]

# Bar chart
plt.figure(figsize=(8, 6))
bars = plt.bar(methods, accuracies, color=['red', 'green'])

# Add value labels on top of the bars
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 1, f'{height:.2f}%',
             ha='center', va='bottom', fontsize=12)

# Chart details
plt.title('Accuracy Comparison: Attacker Model vs Traffic Shaping Defense')
plt.ylabel('Accuracy (%)')
plt.ylim(0, 110)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()

# Show chart
plt.show()

import matplotlib.pyplot as plt

# Defense methods and their corresponding accuracies
methods = [
    "Attacker Model",
    "Method 1 (Dummy Pool)",
    "Traffic Shaping Model",
    "Hybrid Model",
    "MITRA (Santos et al., 2023)",
    "T-SNERF (Hammad et al., 2021)",
    "GIWRF (Khan et al., 2021)",
]

accuracies = [
    99.98,  # Attacker Model
    67.78,  # Method 1 (Dummy Pool)
    77.12,  # Traffic Shaping Model
    63.39,  # Hybrid Model
    48.00,  # MITRA
    98.78,  # T-SNERF
    74.87,  # GIWRF
]

# Create the line chart
plt.figure(figsize=(10, 6))
plt.plot(methods, accuracies, marker='o', linestyle='-', color='blue', label='Accuracy')

# Highlight Method 1 (Dummy Pool)
highlight_index = methods.index("Method 1 (Dummy Pool)")
plt.scatter(methods[highlight_index], accuracies[highlight_index], color='red', s=100, label='Pool of Dummy')

highlight_index = methods.index("Traffic Shaping Model")
plt.scatter(methods[highlight_index], accuracies[highlight_index], color='purple', s=100, label='Traffic Shaping')

highlight_index = methods.index("Hybrid Model")
plt.scatter(methods[highlight_index], accuracies[highlight_index], color='green', s=100, label='Hybrid Method')



# Chart labels and title
plt.title("Comparison of Defense Mechanisms Methods")
plt.xlabel("Defense Methods")
plt.ylabel("Accuracy (%)")
plt.ylim(40, 110)
plt.grid(True)
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Defense methods and their corresponding accuracies
methods = [
    "Attacker Model",
    "Method 1 (Dummy Pool)",
    "MITRA (Santos et al., 2023)",
    "T-SNERF (Hammad et al., 2021)",
    "GIWRF (Khan et al., 2021)",
]

accuracies = [
    99.98,  # Attacker Model
    67.78,  # Method 1 (Dummy Pool)
    48.00,  # MITRA
    98.78,  # T-SNERF
    74.87,  # GIWRF
]

# Create the bar chart
plt.figure(figsize=(10, 6))
bars = plt.bar(methods, accuracies, color='Blue')

# Highlight Method 1 (Dummy Pool) in red and annotate all
highlight_index = methods.index("Method 1 (Dummy Pool)")
bars[highlight_index].set_color('red')

# Annotate each bar
for idx, bar in enumerate(bars):
    height = bar.get_height()
    color = 'red' if idx == highlight_index else 'black'
    plt.text(bar.get_x() + bar.get_width() / 2, height + 1,
             f"{accuracies[idx]}%", color=color, ha='center')

# Chart labels and title
plt.title("Comparison of Defense Mechanisms Methods")
plt.xlabel("Defense Methods")
plt.ylabel("Accuracy (%)")
plt.ylim(40, 105)
plt.grid(axis='y')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Defense methods and their corresponding accuracies
methods = [
    "Attacker Model",
    "Pool of Dummy",
    "Traffic Shaping Model",
    "Hybrid Model",
    "MITRA (Dos Santos et al., 2023)",
    "MAC-traffic Shaping (Alyami et al., 2022)",
    "Tor defense (Rahman et al., 2021)",
]

accuracies = [
    99.98,  # Attacker Model
    55.36,  # Pool of Dummy
    66.00,  # Traffic Shaping Model
    66.42,  # Hybrid Model
    58.00,  # MITRA
    54.00,  # MAC
    38.00,  # Tor Defense
]

# Highlight color mapping with lighter shades
highlight_colors = {
    "Pool of Dummy": "lightcoral",
    "Traffic Shaping Model": "plum",
    "Hybrid Model": "lightgreen"
}

default_color = "lightblue"  # Default for non-highlighted bars

# Create bar chart
fig, ax = plt.subplots(figsize=(12, 6))
bars = ax.bar(methods, accuracies, color=default_color)

# Apply highlight colors and annotate with black text
for idx, bar in enumerate(bars):
    method = methods[idx]
    height = accuracies[idx]
    color = highlight_colors.get(method, default_color)
    bar.set_color(color)
    ax.text(bar.get_x() + bar.get_width() / 2, height + 1.5,
            f"{height:.2f}%", ha='center', color='black', fontsize=9)

# Labels and formatting
ax.set_title("Comparison of Defense Mechanisms Methods", fontsize=16, pad=15)
ax.set_xlabel("Defense Methods", fontsize=12, labelpad=10)
ax.set_ylabel("Accuracy (%)", fontsize=12, labelpad=10)
ax.set_ylim(30, 105)  # Lowered to make all bars visible

# Ticks styling
ax.set_xticks(range(len(methods)))
ax.set_xticklabels(methods, rotation=45, ha='right', fontsize=10)
ax.tick_params(axis='y', labelsize=10)
ax.tick_params(axis='x', labelsize=10)

# Remove gridlines and set white background
fig.patch.set_facecolor('white')
ax.set_facecolor('white')
ax.grid(False)

# Ensure all spines (frame) are visible
for spine in ax.spines.values():
    spine.set_visible(True)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Defense methods and their corresponding accuracies
methods = [
    "Attacker Model",
    "Method 1 (Dummy Pool)",
    "MITRA (Santos et al., 2023)",
    "T-SNERF (Hammad et al., 2021)",
    "GIWRF (Khan et al., 2021)",
]

accuracies = [
    99.98,  # Attacker Model
    67.78,  # Method 1 (Dummy Pool)
    48.00,  # MITRA
    98.78,  # T-SNERF
    74.87,  # GIWRF
]

# Create the bar chart
fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.bar(methods, accuracies, color='lightblue')

# Highlight Method 1 (Dummy Pool) in red and annotate all
highlight_index = methods.index("Method 1 (Dummy Pool)")
bars[highlight_index].set_color('lightcoral')

# Annotate each bar
for idx, bar in enumerate(bars):
    height = bar.get_height()
    color = 'red' if idx == highlight_index else 'black'
    ax.text(bar.get_x() + bar.get_width() / 2, height + 1,
            f"{accuracies[idx]}%", color=color, ha='center')

# Chart labels and title
ax.set_title("Comparison of Defense Mechanisms Methods")
ax.set_xlabel("Defense Methods")
ax.set_ylabel("Accuracy (%)")
ax.set_ylim(40, 105)
ax.set_xticks(range(len(methods)))
ax.set_xticklabels(methods, rotation=45, ha='right')

# Remove gridlines and set white background
ax.grid(False)
fig.patch.set_facecolor('white')
ax.set_facecolor('white')

# Show axis spines (frame)
for spine in ax.spines.values():
    spine.set_visible(True)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Defense methods and their corresponding values
methods = [
    "Number of Rows",
    "Feature Variance",
]

values = [
    56099,             # Length
    598294987,      # Feature Variance
]

# Define bar colors
bar_colors = ['lightblue', 'lightcoral']

# Create the bar chart
fig, ax = plt.subplots(figsize=(6, 3.5))
bars = ax.bar(methods, values, color=bar_colors)

# Set log scale for y-axis
ax.set_yscale('log')

# Annotate each bar with black text
for idx, bar in enumerate(bars):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width() / 2, height,
            f"{int(height):,}", color='black', ha='center', va='bottom', fontsize=9)

# Chart labels and title
ax.set_title("Dataset Used for Defense Development", fontsize=12)
ax.set_xlabel("Feature in 3rd Dataset", fontsize=10)
ax.set_ylabel("Total Value", fontsize=10)
ax.set_xticks(range(len(methods)))
ax.set_xticklabels(methods, rotation=0, ha='center')

# Remove gridlines and set white background
ax.grid(False)
fig.patch.set_facecolor('white')
ax.set_facecolor('white')

# Show axis spines
for spine in ax.spines.values():
    spine.set_visible(True)

# Tight layout
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from google.colab import files

# Upload and load CSV
uploaded = files.upload()
df = pd.read_csv(next(iter(uploaded)))

# Device types and feature columns
devices = [
    "Light Bulb",
    "Magnetic Door Contact Sensor",
    "PIR motion sensor",
    "Smart Air Box"
]

features = [
    "Capture Length", "Frame Length", "TCP Segment Length", "Header Length",
    "Total Length", "Length (UDP)", "Ack Number", "Arrival Time", "Delta",
    "Sequence Number", "Source Port", "Destination Port", "Protocol"
]

# Filter only the selected devices
df_filtered = df[df['Device'].isin(devices)].copy()

# Encode non-numeric values
encoder = LabelEncoder()
for feature in features:
    if df_filtered[feature].dtype == 'object':
        df_filtered[feature] = encoder.fit_transform(df_filtered[feature].astype(str))
    else:
        df_filtered[feature] = pd.to_numeric(df_filtered[feature], errors='coerce')

# Compute average values per device
device_averages = df_filtered.groupby('Device')[features].mean()

# Ensure all devices are present
for device in devices:
    if device not in device_averages.index:
        device_averages.loc[device] = [None] * len(features)

# Sort rows to match desired device order
device_averages = device_averages.loc[devices]

# Fill missing PIR motion sensor values with meaningful integers (e.g., rounded mean of other devices)
for feature in features:
    if pd.isna(device_averages.loc["PIR motion sensor", feature]):
        # Take mean of other devices (exclude PIR motion sensor)
        other_values = device_averages.drop("PIR motion sensor")[feature].dropna()
        if not other_values.empty:
            fill_value = int(round(other_values.mean()))
        else:
            fill_value = 1  # default minimum if all missing
        device_averages.at["PIR motion sensor", feature] = fill_value

# Define pastel colors
device_colors = {
    "Light Bulb": "lightblue",
    "Magnetic Door Contact Sensor": "lightgreen",
    "PIR motion sensor": "plum",
    "Smart Air Box": "lightsalmon"
}

# Plot horizontal bar chart per feature
for feature in features:
    plt.figure(figsize=(8, 3.5))
    avg_values = device_averages[feature]

    # Get color for each device
    colors = [device_colors[device] for device in avg_values.index]

    # Plot bars
    bars = plt.barh(avg_values.index, avg_values, color=colors)

    # Add numeric label
    for bar, val in zip(bars, avg_values):
        label = f"{val:.2f}"
        xpos = bar.get_width() + max(avg_values) * 0.01
        plt.text(xpos, bar.get_y() + bar.get_height()/2, label,
                 va='center', fontsize=9, color='black')

    plt.title(f"Average {feature} by Device", fontsize=12)
    plt.xlabel("Average Value", fontsize=10)
    plt.ylabel("Device", fontsize=10)
    plt.xlim(left=0)
    plt.grid(axis='x', linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt

# Define method names and corresponding accuracies
methods = ["Pool of Dummy", "Traffic Shaping", "Hybrid Method"]
accuracies = [55.36, 70.28, 41.01]  # Replace with your actual accuracy values

# Define colors for each method
colors = ["skyblue", "lightcoral", "mediumseagreen"]

# Create vertical bar chart
plt.figure(figsize=(6, 4), facecolor='white')
bars = plt.bar(methods, accuracies, color=colors)

# Add value labels on top of bars
for bar, acc in zip(bars, accuracies):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
             f"{acc:.2f}%", ha='center', va='bottom', fontsize=10)

# Chart formatting
plt.title("Accuracy Comparison of Defense Methods", fontsize=13)
plt.xlabel("Defense Method", fontsize=11)
plt.ylabel("Accuracy (%)", fontsize=11)
plt.ylim(0, max(accuracies) + 10)
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)

# Remove background grid and frame
plt.grid(False)
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.gca().spines['left'].set_visible(True)
plt.gca().spines['bottom'].set_visible(True)

plt.tight_layout()
plt.show()